### ISSUE TITLE
Question: Can ``` syntax not take hbs, must be html?

### ISSUE THREAD

**Issue by amyrlam** [ember-learn/ember-blog#1005]
## Current Behavior

Reported by @jayjayjpg in PR description https://github.com/ember-learn/ember-blog/pull/1000

> I noticed a build error locally which I was able to resolve by replacing hbs to html in the syntax annotation for one of the code examples in the file. Let me know if I should revert the change if this is not a general build issue and just occurred for me locally and thank you for taking a look!

## Expected Behavior

From https://www.rubycoloredglasses.com/2013/04/languages-supported-by-github-flavored-markdown/ and https://github.com/github/linguist/blob/master/lib/linguist/languages.yml#L2379 it seems like `hbs` should be supported?

**Comment by ijlee2** [comment]
It's confusing, unfortunately, because in other places (e.g. GitHub, dev.to) we can use `hbs`.

Due to an addon used in this repo, we need to use `handlebars` instead of `hbs`. I recommend using the full name such as `javascript` and `typescript` (instead of `js`, `ts`), for consistency.

Maybe, to close this issue, can we:

- Document how to use `` ``` `` in `CONTRIBUTING.md` (or a similar file)
- Replace the language `html` with `handlebars` in the linked pull request

?

cc: @jayjayjpg (regarding [your pull request](https://github.com/ember-learn/ember-blog/pull/1000/files#diff-9eb28dbfb5e07008d975c8239e9093fddda473fef410dfc4207791607cc13b46R47))

**Comment by ijlee2** [comment]
Related:

- https://github.com/ember-learn/ember-blog/issues/857
- https://github.com/ember-learn/ember-blog/pull/862

**Comment by amyrlam** [comment]
Wow, thanks for the context. TIL! Yes we can do that, and I can tag you for a review?

**Comment by ijlee2** [comment]
Yep, certainly.
