### ISSUE TITLE
Pitch: Ember v4 types blog post

### ISSUE THREAD

**Issue by chriskrycho** [ember-learn/ember-blog#1091]
Hey folks,

I’m nearly done with an update to the types on DefinitelyTyped for Ember v4, and thought it'd be nice to share the update as a blog post.

Basic outline (noting that I already have a draft of this mostly done! 🎉):

- announce the update
  - update to minimum supported TS version
  - removal of deprecated APIs
- list of other notable changes
  - improvements to type safety
  - lots of `any` → `unknown`
- upgrade guide
- a "please report bugs on the ember-cli-typescript repo" since we expect
- a note that this lays the foundation for migration into Ember for official support—and that having official support will make these kinds of things clearer and easier in the future

I expect to open the PR on DefinitelyTyped by the end of today, and we can plan to publish the blog post after the PR is merged.

---

cc. @jenweber @locks (please tag whoever else on Framework Core and the Learning team would be helpful here)

**Comment by jaredgalanis** [comment]
Sounds good @chriskrycho! Would you like to do this as a stand-alone blog post or include it as part of the next Ember Times issue (set for publishing on 1/23).

**Comment by chriskrycho** [comment]
@jaredgalanis definitely as a standalone blog post. I think it’ll be nice for folks to be able to reference it, and it’s also going to be 700+ words. (Referencing it *again* in the Ember Times also sounds great!)

**Comment by MelSumner** [comment]
I think there's some question about what this means for the Ember community at large- is this for folks who want to use typescript? will folks be forced to use typescript in the future whether they want to or not? 

It's a common side effect and not unique to this proposal specifically, but it should still be included. 👍 Also let's make sure @wycats is a reviewer so he can confirm that it's on message. 

Thanks for being willing to do a post!

**Comment by chriskrycho** [comment]
As ever, nothing about our plans for TypeScript will ever oblige anyone to use it; we are just making the experience better and better for those who do. And these changes, as with all the others, improve the experience for Ember developers just using JavaScript as well. In this particular case, that means things like: users getting better autocomplete in their editors (from Vim to VS Code, they all use these types under the hood even if users don’t know it and are writing plain JS), users not getting suggestions for deprecated functions that were removed with Ember 4, users getting notices about upcoming v5 deprecations, etc. Additionally, for TS users, this work makes for much better more correctness across many parts of the code.

It is a very big deal to have support for TypeScript for the many Ember users who want it, and it is important that we keep it up to date, and so this is a very significant change worth publicizing to the community.

**Comment by chriskrycho** [comment]
Also, it may be worth stating again, and more explicitly: this is just a blog post about updating our *existing infrastructure* (as maintained by the Types Ember team for the last five years) so that it correctly supports the current version of Ember!

**Comment by MelSumner** [comment]
@chriskrycho idk if you've already done this but go for it 👍
