### ISSUE TITLE
need test for markdown heading hierarchy

### ISSUE THREAD

**Issue by MelSumner** [ember-learn/ember-blog#123]
we need a test so that headings in markdown are conformant with accessibility guidelines. 

- there should only be one `h1` per page
- Headings must be in a valid logical order, meaning `h1` through `h6` element tags must appear in a sequentially-descending order.

References: 
- https://dequeuniversity.com/rules/axe/3.2/heading-order

**Comment by aklkv** [comment]
I have looked around and I think the best way to solve it is to add markdown linter https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md
If this sounds good I will be happy to implement it

**Comment by amyrlam** [comment]
@aklkv I think this is a great idea if you want to implement it (had filed another issue here https://github.com/ember-learn/ember-blog/issues/44). No worries if you don't have time, just let me know!

**Comment by amyrlam** [comment]
(Also, I'm @ amyrlam on Discord if want to discuss there or in #support-ember-times.)

**Comment by aklkv** [comment]
@amyrlam I will take of of this one this week.

**Comment by amyrlam** [comment]
awesome, thanks, keep me posted!
