### ISSUE TITLE
EmberTimes 210

### ISSUE THREAD

**Issue by MinThaMie** [ember-learn/ember-blog#1330]
Releases
- [x] ember-mobile-menu v5
- [x] ember-gesture-modifiers v6
- [x] https://github.com/ember-bootstrap/ember-bootstrap/releases/tag/v6.2.0
- [x] https://github.com/adopted-ember-addons/ember-popper-modifier/blob/main/CHANGELOG.md#v410-2024-02-26
- [x] https://github.com/ember-intl/ember-intl/blob/v6.5.0/ember-intl/CHANGELOG.md#650
- [x] https://github.com/ember-codemods/ember-native-class-codemod
- [x] https://github.com/mainmatter/ember-intl-analyzer/releases/tag/v4.6.0
- [x] https://github.com/typed-ember/ember-cli-typescript/releases/tag/v5.3.0
- [x]  https://github.com/cibernox/ember-basic-dropdown/blob/master/ember-basic-dropdown/CHANGELOG.md#v800-2024-03-12
- [x] https://github.com/cibernox/ember-power-select/blob/master/ember-power-select/CHANGELOG.md#v800-2024-03-12
- [x] https://github.com/cibernox/ember-power-calendar/blob/master/ember-power-calendar/CHANGELOG.md#v100-2024-03-12
- [x] https://github.com/ember-cli-deploy/ember-cli-deploy-s3/releases/tag/v5.0.0-beta.0

New stuff
- [x] https://github.com/jelhan/webpack-subresource-integrity-embroider
- [x] https://github.com/chancancode/ember-serviceable-helper
- [x] https://github.com/bertdeblock/generate-template-registry
- [x] https://github.com/bertdeblock/gember

Noteworthy stuff
- [x] 🔥  GitHub now has full support for syntax highlighting the template tag component authoring format. (.gjs/.gts)
- [x] https://discord.com/channels/480462759797063690/1221113538396028938 showcase channel
- [x] Polaris EmberData tracking issue: https://github.com/emberjs/data/issues/9337

Events
- [x] Ember Europe 
- [x] EmberConf

**Comment by runspired** [comment]
- EmberData shipped types
- EmberData shipped mirror packages
- EmberData shipped data utils for ember (`@warp-drive/ember`)

**Comment by MinThaMie** [comment]
This was shipped :)
