### ISSUE TITLE
Blog post summarizing the Octane release plan

### ISSUE THREAD

**Issue by jenweber** [ember-learn/ember-blog#230]
@wycats and I have been working on a blog post that describes the expected release plan for Octane, and will PR it soon.  Overall, 3.12 is an LTS candidate with no new features (it should finish shipping this week). 3.13 will have all Octane features available (including Tracked), and people can opt in. 3.14 will be Octane, complete with codemods, guides, and changes to the flags for freshly generated apps.

It is possible that changes will be made to this plan, and if that's the case, updates will be made to the post.

**Comment by amyrlam** [comment]
Done with https://blog.emberjs.com/2019/08/15/octane-release-plan.html?

**Comment by amyrlam** [comment]
Seems like this can be closed - and congrats! 

Please reopen if I'm wrong!
