### ISSUE TITLE
[emberify] Add netlify redirects for all of the old urls to the new content

### ISSUE THREAD

**Issue by kennethlarsen** [ember-learn/ember-blog#232]
When the emberification project is done all of the URLs for the posts will change but we need to make sure that we have the correct redirects in place so we don't have any negative effects on SEO.

For example the current URL for a post on the blog is https://blog.emberjs.com/2019/08/09/the-ember-times-issue-110.html and with empress, the new URL will end up being https://blog.emberjs.com/the-ember-times-issue-110/

We will need to make sure we have [ember-cli-netlify](https://github.com/shipshapecode/ember-cli-netlify) installed and we will need to write a script to populate the .netlifyredirects file with the correct content. The content conversion script will maintain the publish date of all the posts so we should be able to build the redirects from the frontmatter data effectively.

**Comment by kennethlarsen** [comment]
Still good, my robot friend

**Comment by mansona** [comment]
This is done now 🎉  it is a commit in the https://github.com/ember-learn/ember-blog/pull/7
