### ISSUE TITLE
Ember Times emoji don't appear on Windows

### ISSUE THREAD

**Issue by amyrlam** [ember-learn/ember-blog#337]
Screenshot from @MelSumner on Windows browser:
![image](https://user-images.githubusercontent.com/1372946/68148670-4cc40900-fef1-11e9-9854-b273262fa26a.png)

See: 
https://twemoji.twitter.com/
https://superuser.com/questions/1094188/how-do-i-display-the-latest-unicode-characters-esp-emoji-in-windows-browsers

**Comment by amyrlam** [comment]
@MelSumner assigned to you to check on your machine. Here's what I tried on webpagetest, couldn't repro in IE11 (chose Ireland cause had IE11 option): https://www.webpagetest.org/result/191104_VM_b88bec88be0d98b42ea842616cbb11a7/

**Comment by amyrlam** [comment]
@MelSumner I have access to Browserstack through work!

Emojis work with Windows 10, Chrome 78.

![image](https://user-images.githubusercontent.com/1372946/68517765-b9b30800-023d-11ea-964c-0ea151e1928e.png)

I can repro on Windows XP, Chrome 49...but it says Chrome will no longer be supported on Windows XP or Vista.

![image](https://user-images.githubusercontent.com/1372946/68517818-f252e180-023d-11ea-8c71-911e7fcc6d4f.png)

Windows 7, Chrome 78: some emojis work, some don't:

![image](https://user-images.githubusercontent.com/1372946/68517889-3c3bc780-023e-11ea-8ed9-1a6d0ae81002.png)

I found http://caniemoji.com/microsoft-windows/, but I don't see too many solutions recommended.

![image](https://user-images.githubusercontent.com/1372946/68518005-df8cdc80-023e-11ea-9ba1-40a8950f7f75.png)
 
So...seems like maybe https://twemoji.twitter.com/ is the answer, and I will try to take a stab at that soon.

**Comment by MelSumner** [comment]
@amyrlam I don't mind closing the issue - we shouldn't really support Windows 7.

**Comment by amyrlam** [comment]
@MelSumner sure, sounds good, will close then. Thanks for the reply / report! Hope it's working for you now then?
