### ISSUE TITLE
Ember Times doubly curlies appear as-is on goodbits.com

### ISSUE THREAD

**Issue by amyrlam** [ember-learn/ember-blog#344]
## Current Behavior
Syntax to convert `{{` to appear correctly in emails, literally appears as `{{ opening_double_curly() }}` on https://the-emberjs-times.ongoodbits.com/2019/10/12/issue-119

## Possible Solution
I have a support ticket open with Goodbits. Waiting to hear back from 11/2 reply from me. Was reported by @alexlafroscia. (To be honest, I never actually check the Goodbits site...am usually checking our blog and the emails themselves!)

Go to a different email provider. Don't know of any good alternatives yet.

**Comment by alexlafroscia** [comment]
For context, I noticed this because I prefer to subscribe to newsletters through RSS when possible to keep my email inbox clean! That’s the way they render in my RSS reader.

**Comment by amyrlam** [comment]
Ah that makes sense, thanks!

So I have an idea...I guess we need to put code snippets in Goodbits as images (manually), we could make them from carbon e.g. https://carbon.now.sh/wZJBek838rkZgUSHc3Pj cc @jessica-jordan 

We can't fix the old ones in Goodbits but this would be cool going forward

**Comment by alexlafroscia** [comment]
That’s an interesting idea!

Any concern about the accessibility of code snippets vs. images of text?

**Comment by amyrlam** [comment]
Hm, good point. 

I guess right now, code snippets with double curlies in the newsletter appear wrong if someone reads "Views in Browser" or through RSS. 

I guess I'll try to explore some other providers? It would be a lot faster if we could copy the raw markdown as-is, right now we use https://github.com/ember-learn/ember-times-tools

**Comment by amyrlam** [comment]
Pinged Goodbits again to see if they have any ideas / workarounds.

Perhaps we can push people to read RSS on our own blog emberjs.com/blog instead. 

But ideally, we would then want the "View in browser" link to link to emberjs.com/blog instead of Goodbits.

**Comment by amyrlam** [comment]
Pinged Goodbits again to see if any response

**Comment by amyrlam** [comment]
From email correspondence, Goodbits is exploring a code block option! Watch this space

**Comment by amyrlam** [comment]
Pinning issue. Need to switch to new provider, maybe Mailchimp. If provider can take Markdown, would be 💯

**Comment by amyrlam** [comment]
I want to explore moving to Mailchimp one day, but will close this as a known issue for now, apologies

**Comment by amyrlam** [comment]
I don't think Goodbits will solve this.

I set up a basic Mailchimp. Need to check if there's any gotchas with moving the email list from one platform to another. Goal is to trial this, then move to Mailchimp.

**Comment by abhilashlr** [comment]
Sounds good @amyrlam 👍

**Comment by amyrlam** [comment]
New issue with new path forward: https://github.com/ember-learn/ember-blog/issues/734
