### ISSUE TITLE
Create a blog post for December 7, 2019 about the `ember-animated` addon

### ISSUE THREAD

**Issue by MelSumner** [ember-learn/ember-blog#371]
## Goal
Write a short blog post for the December blog series that is similar to the [example post]( https://github.com/ember-learn/ember-blog/blob/be8f29ba0ae8b5367d1758b1a150c1b503812a77/source/2019-12-01-countdown-to-the-new-year-ember-sortable.md).

## Criteria

-  [ ] file name should 2019-12-DD-countdown-to-the-new-year-ADDON-NAME.md where DD is replaced with the day and ADDON-NAME is replaced with the hyphenated name of the addon
- [ ] The opening sentence should be updated where COUNT is the sequential ordinal word. 

```
<b>This is the COUNT in our DecEmber series- <i>"Countdown to The New Year: 31 Days of 
Ember Addons"</i>.  We plan to highlight a new addon each day until the new year, and 
we hope you'll join us for the fun!</b>
```

- [ ] The first h2 should be "Day NUM" where NUM is the same as the DD in the date.
- [ ] the link to the addon should point to the page on Ember Observer
- [ ] There should be two sub sections: (both h3)- "What it does" and "Why I like it" 
- [ ] Include whether or not the addon has been updated yet for Ember Octane- if not, invite contributors to help get the addon Octane ready.
- [ ] The closing sentence can be slightly altered but should feel similar: 
"Do you use this addon? Or one like it? We'd love to hear about Ember addons that bring you joy!"

**Comment by jenweber** [comment]
Hi, I would love to write about this one!

**Comment by MelSumner** [comment]
Thanks @jenweber !
