### ISSUE TITLE
Create a blog post for December 13, 2019 about the `ember-simple-auth` addon

### ISSUE THREAD

**Issue by MelSumner** [ember-learn/ember-blog#379]
## Goal
Write a short blog post for the December blog series that is similar to the [example post]( https://github.com/ember-learn/ember-blog/blob/be8f29ba0ae8b5367d1758b1a150c1b503812a77/source/2019-12-01-countdown-to-the-new-year-ember-sortable.md).

## Criteria

-  [ ] file name should 2019-12-DD-countdown-to-the-new-year-ADDON-NAME.md where DD is replaced with the day and ADDON-NAME is replaced with the hyphenated name of the addon
- [ ] The opening sentence should be updated where COUNT is the sequential ordinal word. 

```
<b>This is the COUNT in our DecEmber series- <i>"Countdown to The New Year: 31 Days of 
Ember Addons"</i>.  We plan to highlight a new addon each day until the new year, and 
we hope you'll join us for the fun!</b>
```

- [ ] The first h2 should be "Day NUM" where NUM is the same as the DD in the date.
- [ ] the link to the addon should point to the page on Ember Observer
- [ ] There should be two sub sections: (both h3)- "What it does" and "Why I like it" 
- [ ] Include whether or not the addon has been updated yet for Ember Octane- if not, invite contributors to help get the addon Octane ready.
- [ ] The closing sentence can be slightly altered but should feel similar: 
"Do you use this addon? Or one like it? We'd love to hear about Ember addons that bring you joy!"

**Comment by ijlee2** [comment]
@MelSumner Because [this addon](https://github.com/ScottLNorvell/ember-tetris) hasn't been maintained in a while and its readme doesn't have good instructions for installation and use, I'm not sure if we should include it in the DecEmber series.

I tried installing it on a 3.14 app but am running into deprecation warnings (ember-cli-babel) and an error `'/Users/isaac/Desktop/my-tetris-app/bower_components/ember/ember-template-compiler.js'` that seems to want me to install Bower and possibly work on some configuration.

I would have liked to see the addon just work so that I could write this piece. Hidden Easter eggs are awesome. :)

**Comment by ijlee2** [comment]
My bad, I take back on instructions. The author has another repo: https://github.com/ScottLNorvell/ember-tetris-addon

**Comment by acorncom** [comment]
@ijlee2 that addon **also** hasn't been updated in a tad over four years, so I think your comment likely still holds ...

**Comment by ijlee2** [comment]
Yeah. Hmm..

**Comment by MelSumner** [comment]
@ijlee2 @acorncom hmm okay. Do you have a different addon you'd like to recommend in its place?

**Comment by ijlee2** [comment]
My favorite addons (ember-test-selectors & ember-exam) are already covered. 😄 Maybe ember-truth-helpers, or ember-percy if this can be considered an addon?

I haven't used these addons but, from what I've seen over chats, think they provide value to the community. Maybe somebody has enjoyed using it and can cover writing about it?
- ember-infinity
- ember-simple-auth

Thanks,

**Comment by MelSumner** [comment]
infinite scrolling is bad for accessibility, but maybe `ember-simple-auth`. I'll update the title.

**Comment by ijlee2** [comment]
Ok, sounds good. Thanks!

**Comment by jayjayjpg** [comment]
I just checked with @sdebarros and she would be up for writing about this one today - I can also help with the review and publishing
