### ISSUE TITLE
Create a blog post about the `ember-mapbox-gl` addon for December 21, 2019

### ISSUE THREAD

**Issue by allthesignals** [ember-learn/ember-blog#406]
[Ember Mapbox GL](https://github.com/kturney/ember-mapbox-gl) is great tool for quickly adding modern maps to your application in a declarative, composable way.

I'd be happy to contribute a post on it! A similar addon, https://miguelcobain.github.io/ember-leaflet/docs, includes a great outline for introducing mapping concepts under its Guides header. Something like this could be a starting point for this post.

Other topics: 
 - Putting a dot on the map
 - Using templates to manage map state
 - Using services to manage "main map" state
 - Perils of interacting with the map on route events (and solutions)

**Comment by MelSumner** [comment]
That would be great! Please check the other issues for this series to see what the template requirements are. Thank you <3

**Comment by MelSumner** [comment]
@allthesignals if you could get a PR in soon, that would be awesome. We'll take care of the editing and publishing on the 21st so if you're not around you don't have to worry about it. Thank you for writing this!

**Comment by allthesignals** [comment]
@MelSumner woops! will do. will finish this weekend. thank you!

**Comment by MelSumner** [comment]
@allthesignals can you DM me on Discord so we can work out where to put this? I realized that we didn't publish it yesterday. Thank you!

**Comment by MelSumner** [comment]
Resolved with #466
