### ISSUE TITLE
Add update on co-location for 3.13

### ISSUE THREAD

**Issue by kennethlarsen** [ember-learn/ember-blog#424]
Currently, we state in the 3.13 release post (https://blog.emberjs.com/2019/09/25/ember-3-13-released.html) that co-location is only available with the Octane preview enabled. 

With https://github.com/ember-cli/ember-cli-htmlbars/pull/384 this is no longer true.

Once merged, we should add an update to the release post stating that the preview is no longer assumed to avoid confusion when upgrading.

**Comment by amyrlam** [comment]
@kennethlarsen Not quite sure what you mean, but looks like https://github.com/ember-cli/ember-cli-htmlbars/pull/384 is merged, should we proceed? Just checking in on the repo as missed the cleanup party sadly

**Comment by kennethlarsen** [comment]
@amyrlam Ah yes, forgot about this! https://blog.emberjs.com/2019/09/25/ember-3-13-released.html should now be updated with a note saying that co-location is now available without the Octane preview.

**Comment by amyrlam** [comment]
👍 have a long weekend coming up, but i can help next week
