### ISSUE TITLE
Add ids for goodbitsing to the blog

### ISSUE THREAD

**Issue by jayjayjpg** [ember-learn/ember-blog#45]
Related to https://github.com/ember-learn/ember-times-tools/issues/23

## Current Behavior

The goodbits script for transferring an Ember Times blog post to the newsletter is not working anymore. The reason the script doesn't work anymore is because the styling of the blog and its classes have changed dramatically,

## Expected Behavior

To make sure that the script can run reliably in the future and is independent from style changes, please add a set of identifiers to the different sections on the blog that are meant to be used specifically by the goodbitsing script: https://github.com/ember-learn/ember-times-tools

## Steps to Reproduce

1.
2.
3.

**Comment by amyrlam** [comment]
Good to close, since everything working a-ok?

**Comment by amyrlam** [comment]
will close for now
