### ISSUE TITLE
Fix the spellcheck - tests aren't running or don't fail the tests, and they should

### ISSUE THREAD

**Issue by jenweber** [ember-learn/ember-blog#527]
## Current Behavior
I had a PR with a spelling error, `addomn` instead of `addon`, yet all tests were green.

## Expected Behavior
The test suite should have failed.

## Steps to Reproduce
Look at a PR with a typo: https://github.com/ember-learn/ember-blog/pull/526

**Comment by amyrlam** [comment]
To follow-up from Discord, I don't think this was set up on the repo before, but maybe it was way back when. We can explore a Ruby-based solution

> I thing there was one on the old guides when it was a ruby app

When we go to the new blog setup, could use a JS one e.g. the guides currently uses https://github.com/maxwondercorn/ember-dictionary#readme
