### ISSUE TITLE
Ember pic no longer showing up on Twitter

### ISSUE THREAD

**Issue by amyrlam** [ember-learn/ember-blog#551]
## Current Behavior
Heads up looks like the image metadata isn't returning
https://emberjs.com/images/brand/ember_E-Icon-4c-Square-b850e602fd69b4bfbc1b129f62901be6.png
<meta property="og:image" content="https://emberjs.com/images/brand/ember_E-Icon-4c-Square-b850e602fd69b4bfbc1b129f62901be6.png">
Its what we look for to display some image when sharing the link

reported by @chrisrng 

IS:
![image](https://user-images.githubusercontent.com/1372946/75736790-fefaba00-5cb2-11ea-8f9d-a2a77c0e66d2.png)

## Expected Behavior

Should be: Twitter "card" has image

**Comment by chrisrng** [comment]
I think we were relying on the old ember website and when it went live the image URL probs also went down.

I see it live here: https://emberjs.com/images/brand/ember_E-Icon-4c-Square.png

**Comment by amyrlam** [comment]
It looks fixed here: https://cards-dev.twitter.com/validator

prob just takes a bit to update on https://twitter.com/embertimes

**Comment by chrisrng** [comment]
Looking good for linkedin too using post inspector

https://www.linkedin.com/post-inspector/

**Comment by amyrlam** [comment]
talked on discord, let's close via https://github.com/ember-learn/ember-blog/pull/552
