### ISSUE TITLE
Blog series for Global Accessibility Awareness Day

### ISSUE THREAD

**Issue by rajasegar** [ember-learn/ember-blog#628]
This came out of a discussion in #st-a11y channel about doing an A11y blog post series  for GAAD ( Global Accessibility Awareness Day) https://globalaccessibilityawarenessday.org/

The idea is to publish a blog post each day from May 1 - 21 with the following topics, one topic/day. This will open up a lot of ways for Ember developers to know more about A11y and inturn to create awareness about the subject. Willing to collaborate on any topic with other people.
@MelSumner wanted to check with the blog team so that the folks can respond with the topic they'd like to write about, hence creating an issue for the same here.

- [ ] What & Why of Accessibility
- [ ]  The POUR model
- [ ]  Color contrast
- [ ]  Keyboard accessibility
- [ ]  Screenreaders
- [ ]  Ember & A11y
- [ ]  Ember Addons for A11y
- [ ]  WCAG
- [ ]  Laws, standards, and guidelines with respect to A11y
- [ ]  WAI-ARIA recommendations
- [ ]  Browser extensions for A11y
- [ ]  Testing A11y - how & why (:lock: @praskovia-root)
- [ ]  Images & Alt
- [ ]  Forms & Labels
- [ ]  ARIA
- [ ]  Headings 
- [ ]  Regions & Landmarks
- [ ]  Links, skip links
- [ ]  Language & A11y, lang attribute, etc.,
- [ ]  Resources - websites, blogs, newsletters, etc.
- [ ]  People - We can talk about some of the most prominent people working on Web Accessibility and what kind of impact they  are creating for the community.

**Comment by amyrlam** [comment]
@rajasegar Awesome! Do you want us to plug this initiative in Friday's Ember Times issue e.g. a call for writers, if you are looking for them? lmk

**Comment by rajasegar** [comment]
@amyrlam Yes, definitely. That would be great to have more people pitching in for the posts.
@MelSumner Your thoughts?

**Comment by abhilashlr** [comment]
@rajasegar quick suggestion, if we agree upon this list, can we make it a TODO checklist? It is something that is followed in the Ember times PR. If someone opts to write on it, the same item can be assigned to individuals?

**Comment by rajasegar** [comment]
@abhilashlr done

**Comment by praskovia-root** [comment]
I'd love to write about the a11y testing topic.

**Comment by amyrlam** [comment]
👍 I went ahead and added @praskovia-root to testing above, hope that's ok!

**Comment by amyrlam** [comment]
@MelSumner @rajasegar @abhilashlr and team: I meant to submit a PR but committed to the branch instead by accident. Let me know if you have any feedback! Will go out in tomorrow's issue. https://github.com/ember-learn/ember-blog/pull/624/commits/9cb6cee9bd1140f583569be890d6f0a9080a2f8a

**Comment by rajasegar** [comment]
This looks fine to me, I think the quicker we sent this out the better. I will wait for the feedback from the rest of the team.

**Comment by abhilashlr** [comment]
Hi @amyrlam, the content reads great 🏆 but a minor spelling mistake for `Accessbility` which should read`Accessibility`: https://github.com/ember-learn/ember-blog/commit/9cb6cee9bd1140f583569be890d6f0a9080a2f8a#diff-f65b76e052450eb1f2c8de7d93eb4892R43

**Comment by amyrlam** [comment]
I'll close this as the post is up! https://blog.emberjs.com/2020/05/21/global-accessibility-awareness-day.html
