### ISSUE TITLE
Provide guidance about SEO in Ember apps

### ISSUE THREAD

**Issue by MelSumner** [ember-learn/ember-blog#629]
All of the search results that show up for "Ember SEO" are either outdated or lead to misleading websites. Suggest a new blog post is written to provide a current perspective on SEO for modern Ember apps. 

(h/t to @mansona for making us aware of the issue)

**Comment by amyrlam** [comment]
The topic of SEO was mentioned here: https://blog.emberjs.com/2020/06/26/the-ember-times-issue-154.html, in https://abhilashlr.in/ember-performance-tweaks-part-3
