### ISSUE TITLE
Add publishing instructions

### ISSUE THREAD

**Issue by amyrlam** [ember-learn/ember-blog#752]
We have https://github.com/ember-learn/ember-blog/blob/master/source/CONTRIBUTING.md, but should add separate instructions for publishing (with the caveat that, that process will change if can move off of Goodbits!)

* There are some notes at the bottom of the PR e.g.

```
✅ Publishing TODOs:

 Ensure no use of Markdown italic, use <span style="font-style: italic;"> instead
 Check Netlify preview e.g. buttons, to ensure display on emberjs.com/blog is good
 Crosspost on dev.to, delete any alex, redo any span italics, manually redo Readers Question picture, add Canonical URL
 Set up tweet for Monday morning on tweetdeck
 Post $natural for #news-and-announcements in Discord
```

* Some instructions in ember-times-tools README: https://github.com/ember-learn/ember-times-tools

This can be an ongoing project, just want to document and add to https://github.com/orgs/ember-learn/projects/18 so it's not all in my head

cc @ijlee2 @jaredgalanis

**Comment by amyrlam** [comment]
- [x] Some instructions are on the ongoing latest issue PR: https://github.com/ember-learn/ember-blog/pulls?q=is%3Apr+is%3Aopen+label%3A%22%F0%9F%97%9E+embertimes%22
- [x] Some instructions here https://github.com/ember-learn/ember-times-tools 
  - [x] Ideally move away from Goodbits and archive this repo. I probably won't have time to pick this up again til after the next 9/11 issue, which seems a-ok to me! 
  - [x] Move other instructions for dev.to and Twitter here, keep testing with new publishers and see if they make sense.

**Comment by ijlee2** [comment]
- [x] Create `CONTRIBUTING.md` file with basic information
- [x] Update `CONTRIBUTING.md` to explain how to write for The Ember Times
- [x] Update `CONTRIBUTING.md` to explain how to publish The Ember Times issue
- [x] Remove duplicate instructions

**Comment by amyrlam** [comment]
I think https://github.com/ember-learn/ember-blog/pull/891 will cover everything. Let me know if you have any feedback!
