### ISSUE TITLE
convert inline styles in ember-homepage-survey.md to use new grid classes

### ISSUE THREAD

**Issue by mansona** [ember-learn/ember-blog#828]
The pictures on https://deploy-preview-7--ember-blog-legacy.netlify.app/ember-homepage-survey/ should be side-by-side. See https://blog.emberjs.com/2018/07/30/ember-homepage-survey.html for reference.

use the layout and lg:col-2 for each column 

**Important** create a PR that targets the conversion PR that will be merged into master right after the release.

**Comment by jenweber** [comment]
Visiting https://5fde6151a7a5b100076ccab3--ember-blog-legacy.netlify.app/2018-ember-community-survey.html/

Broken link
https://5fde6151a7a5b100076ccab3--ember-blog-legacy.netlify.app/ember-community-survey-2018
