### ISSUE TITLE
Add meta image

### ISSUE THREAD

**Issue by amyrlam** [ember-learn/ember-blog#854]
## Current Behavior
We've lost the meta image on https://twitter.com/embertimes/status/1341045755323305985

## Expected Behavior

Show the Ember "e", white on orange background

**Comment by ijlee2** [comment]
Should be fixed by #873 .

**Comment by amyrlam** [comment]
@ijlee2 @chrisrng thanks! I ran the latest blog link thru https://cards-dev.twitter.com/validator to "refresh" Twitter and it looks good on https://twitter.com/embertimes now!
