### ISSUE TITLE
$ character escapes to ¨D in code blocks

### ISSUE THREAD

**Issue by ijlee2** [ember-learn/ember-blog#863]
## Description

For some reason, the character `$` (e.g. from jQuery's `$()`) gets rendered as `¨D` in a code block. The following screenshot came from the URL [https://blog.emberjs.com/ember-2-2-released/](https://blog.emberjs.com/ember-2-2-released/).

<img width="720" alt="Screen Shot 2020-12-22 at 10 58 41 AM" src="https://user-images.githubusercontent.com/16869656/102913667-b7f9d300-4444-11eb-93cf-d60e1c38dd56.png">

I tried to escape the character by typing `\$`, `\\$`, and `$$`; however, none of these seemed to work. Please investigate the cause and how we can fix it.

**Comment by nickschot** [comment]
I tracked it down to prismjs itself, very likely the javascript language component. We integrate with prism in ember-showdown-prism (call the prism highlight function) instead of relying on the global so something might still be going on there.

I'm trying to track it down further.

**Comment by nickschot** [comment]
I think I understand what's going on. Our custom Prism showdown plugin does not take "D as a single character and as such "highlights" it's syntax, meaning the regex won't find it afterwards anymore to replace it. Best solution is probably to replace these characters with their originals before passing to prism, and then replacing them again with their substitutes. We'll need to do this for:

```
    // attacklab: Restore dollar signs
    text = text.replace(/¨D/g, '$$');

    // attacklab: Restore tremas
    text = text.replace(/¨T/g, '¨');
```

I'll make a PR to ember-showdown-prism.

**Comment by nickschot** [comment]
Will be fixed by https://github.com/empress/ember-showdown-prism/pull/13

**Comment by amyrlam** [comment]
Removed `stale` saw the upstream PR still open!
