### ISSUE TITLE
Page title doesn't update after navigating to another page

### ISSUE THREAD

**Issue by ijlee2** [ember-learn/ember-blog#875]
## Demo

After landing on [Ember 3.22 Release](https://blog.emberjs.com/ember-3-22-released), try clicking on the link for `Ember 3.23 Release` under Releases tag. You will see that the title remains as `Ember 3.22 Released`.

![recording](https://user-images.githubusercontent.com/16869656/103522635-f480f200-4e7a-11eb-86bd-8f6404cfbc45.gif)

**Comment by nickschot** [comment]
I've identified this as a bug in empress-blog itself. It seems https://github.com/empress/empress-blog/blob/master/addon/services/head-data.js#L20 this computed property does not have the correct dependencies set up to detect changes to the model. It'll need to become two CP's.

**Comment by nickschot** [comment]
Will be fixed in https://github.com/empress/empress-blog/pull/102 . We'll need to update the empress-blog dependency once it has been released.
