### ISSUE TITLE
Do we want to limit Ember Times to quantity one in "Recent Posts"

### ISSUE THREAD

**Issue by amyrlam** [ember-learn/ember-blog#888]
## Current Behavior

We manually set it in the prior version of the blog so that there would only be one Ember Times issue listed. 

![image](https://user-images.githubusercontent.com/1372946/104798057-4decf900-5778-11eb-8cf1-c7ef886f83a0.png)

## Expected Behavior

One Ember Times issue max under "Recent Posts"

**Comment by ijlee2** [comment]
@amyrlam I think adding the feature isn't necessary, given that we show 3 recent posts. It may make testing difficult as well (easier to test that a list of items is displayed in publication date order only).

Would it be okay with you if we close this issue? (We can reopen it if there are more people from the community who want to see this feature.)

**Comment by amyrlam** [comment]
@ijlee2 yes fine with me! This was implemented on the old blog from a complaint before, we could reopen it if someone feels strongly.
