### ISSUE TITLE
Post-Substack move stuff

### ISSUE THREAD

**Issue by amyrlam** [ember-learn/ember-blog#899]
- [x] If Substack goes well, close Goodbits account, particularly be sure to end @tylerturdenpants payment (thank you!) as Substack is free.
- [x] If Substack goes well, archive https://github.com/ember-learn/ember-times-tools, is no longer needed. I moved the Twitter / dev.to instructions here
- [x] Amy: Update these instructions next send, 2/5

**Comment by amyrlam** [comment]
Tagged @tylerturdenpants on Discord and closed out Goodbits! 

Archived https://github.com/ember-learn/ember-times-tools repo cc @ijlee2 

Will run thru the instructions tmrw and update as needed

**Comment by ijlee2** [comment]
@amyrlam Much thanks for leading the initiative to migrate the email service!
