### ISSUE TITLE
Have `2021` be "by year" instead of "by subject"

### ISSUE THREAD

**Issue by amyrlam** [ember-learn/ember-blog#912]
## Current Behavior

![image](https://user-images.githubusercontent.com/1372946/107841309-d4dcc380-6d6e-11eb-9a3f-e65ea5d9858f.png)

Look into if it's this repo or on Empress.

**Comment by mansona** [comment]
I'm pretty sure that it just needs to be added to this list and then it will start working: https://github.com/ember-learn/empress-blog-ember-template/blob/master/addon/components/tag-panel.js#L7
